# This is a basic workflow to help you get started with Actions

name: First Workflow                                               
on: pull_request                                                  
jobs:                         
  first-job:                           
    name: Say hi                           
    runs-on: ubuntu-latest                           
    steps:                           
    - name: Print a greeting                             
      run: echo Hi from our first workflow!
