# This is a basic workflow to help you get started with Actions

name: First Workflow                                               
on: pull_request                                                  
jobs:                         
  first-job:                           
    name: Say hi                           
    runs-on: ubuntu-latest                           
    steps:                           
    - name: Print a greeting                             
      run: echo Hi from our first workflow!
      
    name: First interaction
    uses: actions/first-interaction@v1.1.0
    # Comment to post on an individual's first issue
    issue-message: Thank you for highlighting issue.
    # Comment to post on an individual's first pull request
    pr-message: Thank you.
